clojure-emacs/refactor-nrepl

- README.md
- src/refactor_nrepl/client.clj
- src/refactor_nrepl/ns/resolve_missing.clj
- test/refactor_nrepl/integration_tests.clj
This also removes an assumption that capitalized names belong to
classes.  This prevented the resolution of e.g. schemas from
prismatic/schema, which are vars that conventionally start with capital
letters.
The return value of the op has changed.  We're now dropping :type because
it no longer contains the resolution we need on the client side.  We have
to be able determine the difference between a missing:
1) record or type, as created by defrecord or deftype, respectively
2) class
3) ns
The new return value is thus an alist of ((candidate1 . type1) (candidate
2 . type2) ...), where type is in #{:type :ns :class}.
A :type is generated by both defrecord or deftype becaues the client will
do the same in both cases.
Interfaces are included under :class because info-clj doesn't make the …
> Fix resolve-missing for records and types

- README.md
- src/refactor_nrepl/artifacts.clj
- src/refactor_nrepl/client.clj
- src/refactor_nrepl/find_symbol.clj
- src/refactor_nrepl/plugin.clj
- test/refactor_nrepl/integration_tests.clj
- Rename refactor.clj => find_symbol.clj
- Create a new toplevel op find-symbol
- Create a new toplevel op find-debug-fns
- Change the name of some of the parameters to find-symbol:
loc-line => line, loc-column => column, clj-dir => dir
- The return value of find-symbol is changed from [4 4 3 20 println ...]
to a plist with the following keys: :line-beg :line-end :col-beg
:col-end :name :path :match.
- Expanded the readme to better document find-symbol
> [Fix #29] Split refactor into several ops

- resources/testproject/src/com/example/five.clj
- src/refactor_nrepl/analyzer.clj
- src/refactor_nrepl/client.clj
- src/refactor_nrepl/find_symbol.clj
- src/refactor_nrepl/find_unbound.clj
- src/refactor_nrepl/util.clj
- test/refactor_nrepl/integration_tests.clj
- refactors bits of find symbols to reuse in find unbound
- rework of extract fn, rel to clojure-emacs/clj-refactor.el#103 and
#15
- analyzes a s-expression child of the top level form to figure out
what would be unbound if the s-expression was top level form
- does not expect a broken ns to analyze
> extract-fn rework: fixes #45

- README.md
- src/refactor_nrepl/analyzer.clj
- src/refactor_nrepl/middleware.clj
This is a dedicated op for warming the ast cache.  This removes the need
for overloading `find-symbol` to also pre-build the cache.
> Add op warm-ast-cache

- README.md
- project.clj
- src/refactor_nrepl/middleware.clj
- src/refactor_nrepl/stubs_for_interface.clj
- test/java/refactor/nrepl/MyInterface.java
- test/refactor_nrepl/stubs_for_interface_test.clj
This returns enough information to create stub implementations of
protocols and interfaces in the client.
Specifically it returns the name of functions to implement as well as
the parameter list.
https://github.com/clojure-emacs/clj-refactor.el/pull/148
> Add op stubs-for-interface

- .gitignore
- README.md
- src/refactor_nrepl/extract_definition.clj
- src/refactor_nrepl/middleware.clj
- src/refactor_nrepl/util.clj
- test/refactor_nrepl/extract_definition_test.clj
- test/refactor_nrepl/test_artifacts.clj
- test/refactor_nrepl/util_test.clj
- test/resources/extract_definition.clj
Given the same input as `find-symbol` `extract-definition` will extract
one of the following definitions:
- let-bound var
- def
- defn
The implementation does not use the reader to extract the definition so
any metadata or comments in the definition body are preserved
> Add op extract-definition 

- README.md
- project.clj
- src/refactor_nrepl/middleware.clj
- src/refactor_nrepl/rename_file_or_dir.clj
- test/refactor_nrepl/integration_tests.clj
- test/refactor_nrepl/rename_file_or_dir_test.clj
- test/resources/testproject/src/com/move/dependent_ns1.clj
- test/resources/testproject/src/com/move/dependent_ns2.clj
- test/resources/testproject/src/com/move/non_clj_file
- test/resources/testproject/src/com/move/ns_to_be_moved.clj
This op is used to move a file or a directory of files.  If any clojure
files are affected by the move any dependent namespaces are updated.
Unlikely tools.namespace's move-ns this op also handles vectors written
in prefix notation as well as fully qualified references in the file
body itself referencing vars from the old namespace.
The return value of the op is a list of the file which were affected by
the move.  This list does not include any deleted files. These files all
have to be visited by the client to indent the changed ns form until we
get proper pretty printing support in the middleware.
This ops is quite slow because it does multiple passes over each file
but it's still orders of magnitude faster than doing this manually so
I'm not that worried about speed in this initial …
> Add rename-file-or-dir

- src/refactor_nrepl/analyzer.clj
I've been having trouble today with refactor-nrepl telling me that many of my namespaces were "in a bad state". Printing the stacktrace showed me that the problem is that the analyser is not taking into account custom tagged-readers defined in `src/data_readers.clj`.
This pull request "fixes" this issue by binding `clojure.tools.reader/*data-readers*` to the current value of `clojure.core/*data-readers*`. I'm not sure if this is really the best way (or place) to solve the issue.
```java
clojure.lang.ExceptionInfo: No reader function for tag year-month {:column 66, :line 96, :file "file:/full/path/to/file/file.name.clj", :type :reader-exception}
at clojure.core$ex_info.invoke(core.clj:4403)
at deps.toolsreader.v0v8v12.clojure.tools.reader.reader_types$reader_error.doInvoke(reader_types.clj: …
```
> Bind clojure.tools.reader/*data-readers* to *data-readers*

- README.md
This snippet properly initializes `refactor-nrepl` in `boot-clj`.
Version `1.0.5` of `refactor-nrepl` does not work properly with Cider `0.9.0`.
> Add `Boot` section in README.md

- project.clj
- src/refactor_nrepl/ns/dependencies.clj
- src/refactor_nrepl/ns/helpers.clj
- src/refactor_nrepl/test.clj
- test/refactor_nrepl/test_namespace.clj
- test/resources/ns2.clj
- test/resources/ns_referencing_macro.clj
The previous implementation relied on the AST to to find some symbols
and a manual walk to find the rest.  Due to the effect of macros we're
already walking so much of the file that we might as well abandon the
AST and walk everything. The new implementation thus walks every form
in the body and collects symbols to use when pruning libspecs and
imports.
The benefit of this approach are as follows
- We're for sure not going to remove a libspec or a referred symbol
which is needed.
- Since we don't rely on an AST the op will work on files that are in a
'bad state'.
- This approach should be a lot easier to adapt to .cljs and .cljc files.
The disadvantage of this approach is that we're going to leave some
symbols and libspecs around in the ns form when they are unused.  This
should be …
> Rewrite clean-ns

- .gitignore
- project.clj
- src/refactor_nrepl/config.clj
- src/refactor_nrepl/middleware.clj
- src/refactor_nrepl/ns/clean_ns.clj
- src/refactor_nrepl/ns/dependencies.clj
- src/refactor_nrepl/ns/helpers.clj
- src/refactor_nrepl/ns/ns_parser.clj
- src/refactor_nrepl/ns/rebuild.clj
- src/refactor_nrepl/rename_file_or_dir.clj
- src/refactor_nrepl/util.clj
- test/refactor_nrepl/integration_tests.clj
- test/refactor_nrepl/ns/ns_parser_test.clj
- test/refactor_nrepl/test_namespace.clj
- test/resources/cljsns.cljs
- test/resources/cljsns_cleaned.cljs
There's now support for:
* pruning of libspecs and imports
* sorting of libspecs and imports
* removal of :use
* :refer-macros are pruned and sorted
* :require-macros are pruned and sorted
* :use-macros are re-written to :require-macros
For now I'm not going to update the readme or  the changelog because this
is likely to still be somewhat rough around the edges.
> Add cljs to clean-ns

- README.md
- src/refactor_nrepl/find/find_macros.clj
- src/refactor_nrepl/middleware.clj
- src/refactor_nrepl/ns/helpers.clj
- src/refactor_nrepl/ns/namespace_aliases.clj
- src/refactor_nrepl/ns/ns_parser.clj
- src/refactor_nrepl/util.clj
- test/refactor_nrepl/ns/namespace_aliases_test.clj
This new op returns information about all the namespace aliases that are
in use in the project.
In cljr-refactor we use this to automatically require the right thing
when the user types something like `util/great-util`.
https://github.com/clojure-emacs/clj-refactor.el/pull/219
> Add namespace-aliases op

- README.md
- src/refactor_nrepl/analyzer.clj
- src/refactor_nrepl/config.clj
- src/refactor_nrepl/middleware.clj
- src/refactor_nrepl/ns/clean_ns.clj
- src/refactor_nrepl/ns/rebuild.clj
- test/refactor_nrepl/config_test.clj
- test/refactor_nrepl/ns/namespace_aliases_test.clj
We no longer store the config state but the receive the config settings
as part of each message form the clients.
This is easier in so many ways.
- Don't have to store state.
- Don't have to deal with config messages
- Don't have to let the user know that config changes don't take effect
until they call a function like `cljr-refresh-middleware-config`
> Rework how config works

- .travis.yml
- project.clj
- src/refactor_nrepl/find/find_macros.clj
- test/refactor_nrepl/find/find_macros_test.clj
- test/resources/testproject/src/com/example/fully_qualified_macro_usage.clj
- test/resources/testproject/src/com/example/macro_def_cljc.cljc
Macros defined in cljc files are now correctly found.  Their usage in
clj files is correctly tracked.
In order to deal with cljc files we're going to require clojure 1.7.
> Make find-macros aware of cljc files, require 1.7

- .gitignore
- README.md
- project.clj
- src/refactor_nrepl/ns/resolve_missing.clj
- test/refactor_nrepl/ns/resolve_missing_test.clj
For now this only handles macros and regular cljs vars.  Adding support
google closure classes will be tackled later.
> Add cljs support to resolve-missing

- src/refactor_nrepl/core.clj
- src/refactor_nrepl/find/find_symbol.clj
- src/refactor_nrepl/middleware.clj
- src/refactor_nrepl/ns/libspecs.clj
- test/refactor_nrepl/integration_tests.clj
- test/refactor_nrepl/ns/namespace_aliases_test.clj
- renames `ns.namespace-aliases` to `ns.libspecs`
- uses indexing pushback reader when parsing the ns from so the location
info is recorded/retained
- gets rid of the temp directory for integration tests
> Fix find symbol in refer regression

- README.md
- It works fine with a path relative to the project root.
- Related to clojure-emacs/clj-refactor.el#287 and clojure-emacs/clj-refactor.el#286
> `clean-ns` doesn't require an absolute path (readme update)

- CHANGELOG.md
- README.md
- src/refactor_nrepl/core.clj
- src/refactor_nrepl/find/find_macros.clj
- src/refactor_nrepl/find/find_symbol.clj
- src/refactor_nrepl/find/find_used_publics.clj
- src/refactor_nrepl/find/util.clj
- src/refactor_nrepl/middleware.clj
- test/refactor_nrepl/find/find_macros_test.clj
- test/refactor_nrepl/find/find_used_publics_test.clj
- test/resources/testproject/src/com/example/protocol_def.clj
- test/resources/testproject/src/com/example/protocol_usage.clj
Finds used publics of namespace A in namespace B. Returns find symbol
like occurrences result. Intended to use for replace refer all. Finds
vars, protocols and macros.
Also adds macro occurrences cache and warm-macro-occurrences-cache.
This is supposed to be warmed at REPL startup by default just like
the AST cache.
Intended to be merged for version 2.1.0
> Find used publics

- src/refactor_nrepl/ns/resolve_missing.clj
- test/refactor_nrepl/ns/resolve_missing_test.clj
Resolve-missing returns a list of candidates. Before this fix, the
cljs-path returned only a single candidate. That's because every
candidate was merged together. We now use `merge-with into` to generate
a list of candidates instead.
> Fix resolve-missing for cljs

- src/refactor_nrepl/plugin.clj
This patch tweaks the dependency checker, so that refactor-nrepl will activate itself normally if one of its dependencies is listed in a project's :exclusions. This enables a user to for instance exclude
org.clojure/clojure and provide a fork, thus taking on all responsibility for providing an adequate version.
> Add support for skipping excluded dependencies

- CHANGELOG.md
- src/refactor_nrepl/artifacts.clj
- src/refactor_nrepl/ns/slam/hound/regrow.clj
- test/refactor_nrepl/ns/resolve_missing_caching_test.clj
resolve-missing internally caches a symbol->namespace mapping. New vars that
were added later are not in the cache, and so can not be found.
This code maintains a list of namespaces that were manipulated through nREPL,
and will recheck these every time, incrementally adding to the cache.
Currently this list of dirty namespaces is append only. It will grow over time,
but should still remain small compared to the whole of all loaded namespaces.
This represents a half way point. This same tracking can be extended for other
cached functions in slam.hound.regrow, such as for imports. When that happens
removing namespaces from the dirty list can only be done when all caches have
been updated or invalidated.
Closes #160 
This is my first PR here, it took some searching around. I'd appreciate any …
> Add dirty namespace tracking for resolve-missing

- .gitignore
- CHANGELOG.md
- README.md
- src/refactor_nrepl/config.clj
- src/refactor_nrepl/ns/prune_dependencies.clj
Some libspecs are side-effecting at load time but appear to be unused
otherwise.  `clean-ns` will need a list of these to ignore.  As such
namespaces might be user-created, and I don't want the responsibility of
maintaining a curated list of every such occurrence, this has to be
user-editable.
> Config setting for exceptional libspecs

- src/refactor_nrepl/core.clj
When a file contains the symbol `'/` (e.g. `(/ 6 2)`), then `symbols-in-file`
through `fix-ns-of-backquoted-symbols` will try to find the prefix of that
symbol. The prefix function thinks the slash is a namespace separator, and
things blow up.
This seems to have been introduced in
3839db7 Fix clean-ns with namespaced keywords
Before `(prefix '/)` would simply return `nil`, this fix restores the old behavior.
> Fix a NullPointerException in nrepl-refactor.core/prefix

- CHANGELOG.md
- src/refactor_nrepl/middleware.clj
Error inherits directly from Throwable, so Errors are not Exceptions, they need
to be handled separately. This category includes RuntimeError,
StackOverflowError, and NoClassDefFoundError.
In regular applications you would not catch these, but in our case letting them
bubble means the nREPL handler dies without returning a response, causing the
client to assume that the operation is taking too long and time out, without any
useful feedback.
This is bad UX, and it makes it hard to diagnose and debug problems like #184.
At least this way the user will see a stack trace that hints at the problem.
Thanks!
> Report problems of type java.lang.Error back to the nREPL client

- CHANGELOG.md
- project.clj
And one more :)
`clean-ns` was failing on namespaces that contain Clojure 1.9 style namespaced maps. Because the included version of tools reader was pretty far out of date. This bumps the version from 0.10.0-alpha3 to 1.0.0-beta4. Namespaced maps are supported since tools.reader 1.0.0-beta3.
Is there a general policy on when to bump dependencies? There are quite a few that could be updated. Also, would it make sense to add a `:1.9` profile to test for Clojure 1.9 compatibility?
Thanks!
> Upgrade clojure.tools.reader to support namespaced map literals

- .travis.yml
- project.clj
Ok, last one (for now) :) I really need to get to work on some other stuff :D
I ran the tests for 1.9, had to add a newer ClojureScript to the profile as well since the version used contained an invalid `ns` form which tripped up the new specs for built-in macros.
I'll wait for Travis to finish the testing for 1.7 and 1.9
> Add a profile to test for Clojure 1.9 compatibility

- project.clj
- src/refactor_nrepl/analyzer.clj
- src/refactor_nrepl/core.clj
- src/refactor_nrepl/extract_definition.clj
- src/refactor_nrepl/find/find_locals.clj
- src/refactor_nrepl/find/find_macros.clj
- src/refactor_nrepl/find/find_symbol.clj
- src/refactor_nrepl/find/util.clj
- src/refactor_nrepl/ns/libspecs.clj
- src/refactor_nrepl/ns/pprint.clj
- src/refactor_nrepl/ns/prune_dependencies.clj
- src/refactor_nrepl/ns/rebuild.clj
- src/refactor_nrepl/rename_file_or_dir.clj
- src/refactor_nrepl/s_expressions.clj
- src/refactor_nrepl/util.clj
This PR is a very low-hanging fruit as far as performance optimizations go. It simply adds type hints to fix all the reflection warnings I could find in the `src/` tree, with only a few exceptions where a file path can be either a `String` or a `java.util.File`. Maybe the `fs` library could be used more liberally for that?
I've also added `*warn-on-reflection*` in project.clj to avoid these in the future.
Unfortunately I do not have any benchmarks to showcase performance improvements. However this branch does allow me to run commands such as `cljr-rename-symbol` on a large project whereas master consistently times out :man_shrugging:
> Fix reflection warnings

- CHANGELOG.md
- README.md
- src/refactor_nrepl/config.clj
- src/refactor_nrepl/core.clj
- test/refactor_nrepl/core_test.clj
This change will allow users to configure refactor-nrepl to ignore
certain paths when finding the dirs on classpath by specifying a seq of
regexes which the paths will be matched against.
Currently refactor-nrepl considers all the .clj files that are reachable
from project root. This is a problem if the project repository includes
example .clj files, if a user has symlinked other clj projects under
'checkouts' or if there are any other files that need to be ignored.
This change is backward compatible and wouldn't affect the current
behaviour in existing installations as the default value is an empty
seq.
This PR addresses the issue #167. 
Will add tests after having the maintainers' thoughts on this approach. 
Before submitting a PR make sure the following things have been done (and …
> Add config for ignoring specific paths

- .travis.yml
to fix hack to use newer version of lein when only lein1 was available
on travis. no confusing exception anymore during environment setup.
follows up changes in clojure-emacs/cider-nrepl#419
> Use lein 2.6.1 on travis

- CHANGELOG.md
- src/refactor_nrepl/middleware.clj
There is probably a more elegant way to delay code loading, but this is the most obvious way I could think of.
These changes drop somewhere between 3 and 5 seconds off of repl startup time for me. Tests pass, but I only did a test of a couple features in emacs by hand. I don't actually use refactor-nrepl very much, so I'm not particularly familiar with how people use it.
clojure-emacs/cider#1717
Thanks!
> delay loading of middleware to speed up startup

- src/refactor_nrepl/artifacts.clj
The neg? check always evaluated to false because the arguments
of the time difference calculation were interchanged.
- [x ] The commits are consistent with our [contribution guidelines](CONTRIBUTING.md)
- [x ] All tests are passing (run `lein do clean, test`)
> Fix invalid stale-check

- project.clj
- test/refactor_nrepl/integration_tests.clj
- test/refactor_nrepl/ns/resolve_missing_test.clj
As per Phil Hagelberg's comment in https://github.com/clojure-emacs/refactor-nrepl/issues/200
One of the dependencies for the version of rewrite-clj that this project
uses causes a non-TLS repository to be used, which is dangerous and will
not work in the next version of Leiningen.
Upgraded to the latest stable to fix the above
Thanks!
> Upgraded rewrite-clj

- project.clj
Upgraded Clojure 1.9.0-xyz to the latest 1.9.0 release.
Checklist
-------
> Latest deps

- src/refactor_nrepl/middleware.clj
This function has been removed from cider-nrepl.
Fixes #212
> Extract `err-info` from cider-nrepl

- src/refactor_nrepl/core.clj
deps.edn added as a one more recognizable project root.
> [Fix #219] deps.edn as recognizable project root

- project.clj
- src/refactor_nrepl/core.clj
- src/refactor_nrepl/ns/slam/hound/search.clj
Orchard has encapsulated the boot information already, so that code can
go. Orchard has already upgraded to support Java9+ too. Additionally,
orchard will receive more long-term maintenance of this code.
> Use orchard for classpath information

- README.md
- src/refactor_nrepl/core.clj
- src/refactor_nrepl/ns/pprint.clj
- src/refactor_nrepl/util.clj
- test/refactor_nrepl/ns/clean_ns_test.clj
- test/resources/ns_with_gen_class_methods_meta.clj
- test/resources/ns_with_gen_class_methods_meta_clean.clj
- test/resources/ns_with_lots_of_meta.clj
- test/resources/ns_with_lots_of_meta_clean.clj
**Original:**
- Was only getting ns metadata
- Using positional information for longhand metadata: assuming it was given right after the ns form (in second position)
- Using a regex on the ns-as-string for shorthand metadata.
- Got confused about gen-class methods metadata (because of the regex) and placed it at the top, thinking it was ns top level metadata.
**PR:**
- Gets metadata from ns and (:gen-class :methods)
- Using (meta), so shorthand and longhand can be mixed
- Prints out the metadata in a sorted order, checking if it can be written in shorthand notation. So `^{:static true}` becomes `^:static`
- Can make newlines (as an option) between entries of longhand metadata: 
```clojure
^{:doc "Some doc"
:author "Author"}
```
OR
```clojure
^{:doc "Short doc" :author "Author"}
```
I …
> Fix #235. allow gen-class methods metadata extraction

- src/refactor_nrepl/ns/slam/hound/search.clj
JDK11 doesn't have system properties "sun.boot.class.path" or "java.ext.dirs".  This fix avoids a null pointer exception in `refactor-nrepl.ns.slam.hound.search`.
> Fix a NullPointerException on jdk11

- .circleci/config.yml
- Makefile
- README.md
- project.clj
I added a Makefile, in attempt to bring this more in line with how the other Clojure projects in the org works. Very similar CircleCI config.
https://circleci.com/gh/shen-tian/workflows/refactor-nrepl
As it stood, the project was tested on Oracle Java 8 and Clojure 1.8 and 1.9 in a single job. I've move that over to OpenJDK 8, added Clojure 1.10 tests, and split them up into separate jobs.
I've tried to add Java 11 tests, but they are not passing. Will jot down some notes so we can investigate. Given that we are not testing on Java 11 right now, this PR is good to go.
Edit: a quick look suggests that #241 addresses the Java 11 issues, as that function is where the tests are failing.
> CircleCI migration

- .circleci/config.yml
- Makefile
- project.clj
- src/refactor_nrepl/config.clj
- src/refactor_nrepl/find/find_macros.clj
- src/refactor_nrepl/find/find_symbol.clj
- src/refactor_nrepl/middleware.clj
- src/refactor_nrepl/ns/prune_dependencies.clj
- src/refactor_nrepl/ns/resolve_missing.clj
- src/refactor_nrepl/ns/slam/hound/regrow.clj
- src/refactor_nrepl/plugin.clj
- test/refactor_nrepl/artifacts_test.clj
- test/refactor_nrepl/core_test.clj
- test/refactor_nrepl/ns/clean_ns_test.clj
- test/refactor_nrepl/rename_file_or_dir_test.clj
- test/refactor_nrepl/s_expressions_test.clj
- test/resources/cljcns.cljc
- test/resources/ns2_cleaned_meta.clj
- test/resources/ns2_meta.clj
- test/resources/testproject/src/com/example/shadowed_macro_usages.clj
Uses the same config as `cider-nrepl`. Also runs cljfmt to fix things that came up.
Splitting the commits to 1) adding the profile/CI job, and 2) actually fixing the formatting.
> Adding cljfmt check

- Makefile
- README.md
- build.sh
- project.clj
mranderson 0.5.x specific config added to the project file as
well. Using resolved tree mode. This means that
mranderson works with a resolved dependency tree and does not create a
deeply nested directory structure, only adds prefixes to all
dependencies. Handles all depedendencies as first level ones and
processes them in a topological order.
Add project prefix in the project file and other config for unresolved
tree mode in case we want to switch to that in the near future
> Upgrade mranderson to 0.5.0

- project.clj
- replace `source-dep` with `inline-dep`
> Upgrade mranderson to 0.5.1

- .gitignore
- project.clj
Hoping this is useful. I've updated the deps as far as possible without breaking tests. Of what remain:
- `cider-nrepl` 0.21 requires `nrepl` 0.6. Moving to these two broke some tests. This might be something to do with the new printing middleware.
- `cljs-tooling` 0.3 changed the varity of a function, as part of its self-hosted cljs change. This looks fixable.
---
Thanks!
> Updating the deps as far as we can without breaking tests.

- src/refactor_nrepl/ns/clean_ns.clj
- src/refactor_nrepl/ns/pprint.clj
- test/refactor_nrepl/ns/clean_ns_test.clj
Allow the client to send both the absolute path and a relative path to a file,
we use the first one that we can find.
The absolute path is used when the client (Emacs) and the JVM are on the same
filesystem/same machine. The second is used when they are not on the same
filesystem (e.g. running nREPL on a remote machine or in a VM), but the JVM runs
in the (mounted) project directory, so that relative file lookups still work.
I failed to run the tests locally. Will see what CI says.
See https://github.com/clojure-emacs/clj-refactor.el/issues/380#issuecomment-484509768
> clean-ns: fall back to :relative-path, when given

- src/refactor_nrepl/ns/clean_ns.clj
Follow up to #251, I had completely forgotten `clojure.core` already has a `find` function.
> Use seek instead of find, the latter already exists in clojure.core

- src/refactor_nrepl/s_expressions.clj
- test/refactor_nrepl/s_expressions_test.clj
- test/resources/testproject/src/com/example/sexp_test.clj
Stumbled upon this bug when working on the POC on the `support-cljs` branch. As I spent long minutes staring at this and counting lines/columns on my fingers I thought better to create a PR and invite a review than just pushing it ;)
The added test in `s-expressions-test` proves the bug. It fails with the previous implementation because although `=` is closer to the point than the actual enclosing sexp it does not enclose the point. The trace for this failure:
```
best (ns resources.testproject.src.com.example.sexp-test) distance 11133 zloc (ns resources.testproject.src.com.example.sexp-test) distance 11133
best (ns resources.testproject.src.com.example.sexp-test) distance 11133 zloc ns distance 11086
best ns distance 11086 zloc resources.testproject.src.com.example.sexp-test distance …
```
> Fix when `get-enclosing-sexp` sometimes selects a non enclosing sexp

- CHANGELOG.md
- src/refactor_nrepl/artifacts.clj
- test/refactor_nrepl/artifacts_test.clj
Fixes #255 
Since the `artifacts/get-clojars-artifacts!` function is written in a way that isn't easily testable I opted out on tests. I would need to refactor the code a bit more to make it possible to write a test for this. Let me know if you'd like me to do that.
The fix is simply to use `keep` instead of `map` - and swallow any exception on `edn/read-string`.
> Add try/catch when reading EDN data

- .gitignore
- CHANGELOG.md
- src/refactor_nrepl/artifacts.clj
> Lower bandwidth at startup

- CHANGELOG.md
- src/refactor_nrepl/core.clj
- src/refactor_nrepl/ns/libspecs.clj
> Improve shadow cljs support

- src/refactor_nrepl/ns/rebuild.clj
Per #272, this function has a bug in it and I checked and it's actually never called, so let's just get remove it :-).
> remove unused function

- src/refactor_nrepl/ns/rebuild.clj
- src/refactor_nrepl/ns/tracker.clj
- test/refactor_nrepl/ns/clean_ns_test.clj
- test/resources/ns_with_npm_strs.cljs
- test/resources/ns_with_npm_strs_clean.cljs
This small change will have all the npm string-style requires grouped together.  I think this is desirable, as npm libraries look and act quite differently from regular clojure requires.
> clean-ns: group together npm deps

- project.clj
- src/refactor_nrepl/core.clj
- src/refactor_nrepl/ns/slam/hound/search.clj
Unfortunately the change was not that straightforward due to how orchard 0.5.4 calculates classpaths and refactored the functions around.
I hope I adjusted the code here well enough to follow all the classpath-related changes in orchard. Let me know if there is something wrong or missing.
> [Fix #265] Update orchard version

- src/refactor_nrepl/find/find_macros.clj
- src/refactor_nrepl/find/find_symbol.clj
- test/refactor_nrepl/find/find_macros_test.clj
I feel like we should have a way to ignore macro analyzer exceptions the same way we do it in `find-global-symbol` here https://github.com/clojure-emacs/refactor-nrepl/blob/75f5255f0e4e701f50d30cc58216e03c2d558905/src/refactor_nrepl/find/find_symbol.clj#L133.
Global symbols / macros analyzing can be really tricky sometimes and it fails with similar errors in some of my own projects too. Unfortunately, setting `cljr-ignore-analyzer-errors flag` is not taken into consideration in macro search process. I tried to improve it here.
> [Fix #275] Honor cljr-ignore-analyzer-errors flag in macros analyzer

- project.clj
- src/refactor_nrepl/analyzer.clj
- src/refactor_nrepl/find/find_symbol.clj
- src/refactor_nrepl/middleware.clj
Before I found a real cause of memory leak I tried to analyze and optimize all the functions that are called within `find-symbol` hoping that one of them was the culprit. Eventually I found this line: `(str/join "/" (remove nil? [full-class (:field node)]))))` which was the direct problem.
Looks like `full-class` may become a really huge map in some cases, huge (or complicated) enough that it cannot be stringified correctly by `str/join` which immediately leads to a memory leak.
Having found the real cause, I didn't rollback all the optimization I did before. Hopefully you will find them useful. If not, I'm happy to roll them back.
> [Fix #278] find-symbol memory leak fix

- CHANGELOG.md
- src/refactor_nrepl/find/symbols_in_file.clj
- test/resources/cljsns.cljs
- test/resources/cljsns_cleaned.cljs
- test/resources/js_literal_ns.cljs
As described in
https://github.com/clojure-emacs/clj-refactor.el/issues/443, it was
impossible to use clj-clean-ns when a js literal was present:
'No reader function for tag js'
One possible solution was to use *default-data-reader-fn* with the
function `(fn [_tag value] value)`. However this had the potential of
swallowing useful error messages when dealing with other undefined
tags.
The chosen solution is to provide a dummy reader function specifically
for the #js tag (and only for the :cljs dialect). Rather than
transforming the provided form into a JS object, it returns the
clojure form, which can then be analyzed normally.
---------
- [N/A] The commits are …
> [clj-refactor.el #443] Add support for js literal

- CHANGELOG.md
- src/refactor_nrepl/s_expressions.clj
- test/refactor_nrepl/s_expressions_test.clj
Uneval nodes throw an UnsupportedOperationException if node/sexpr is
called on them, which will break get-first-sexp if it is given
file-content that starts with `#_ whatever`.
This includes uneval nodes in the set of nodes we should skip when
looking for first & last sexps.
- there is no `CONTRIBUTING.md`, I assume this should be `.github/CONTRIBUTING.md`?
- No! I get:
```
Exception in thread "main" java.lang.RuntimeException: Map literal must contain an even number of forms, compiling:(refactor_nrepl/artifacts.clj:25:1)
```
But I get the same thing on `master`, so I'm not sure what is going on there.
- There is no `./build.sh`. I have installed this with `lein …
> Treat uneval nodes as comments

- .circleci/config.yml
- Makefile
- project.clj
- src/refactor_nrepl/core.clj
- src/refactor_nrepl/find/find_macros.clj
- src/refactor_nrepl/rename_file_or_dir.clj
- test/refactor_nrepl/find/find_macros_test.clj
- test/refactor_nrepl/integration_tests.clj
- test/refactor_nrepl/rename_file_or_dir_test.clj
* Run clj-kondo by a more stable means
* Run Eastwood in CI again
* only src for now, as the `test` setup is a bit intrincate with multiple/nested source-paths
* CI: adopt matrix syntax
* Address most reflection warnings
* All `src/` warnings are gone
> Address most reflection warnings / cleanup CI

- CHANGELOG.md
- project.clj
- src/refactor_nrepl/artifacts.clj
- src/refactor_nrepl/ns/pprint.clj
- test/resources/artifacts_pprinted
- test/resources/ns1_cleaned_and_pprinted
- test/resources/ns_with_gen_class_methods_meta_clean.clj
- test/resources/ns_with_lots_of_meta_clean.clj
Could I trouble you to merge this and cut a snapshot release, @bbatsov?  
Currently on a Windows machine and mranderson doesn't work here so I can't install locally or push to clojars.  Haven't had time to investigate why, but would like to dogfood these changes prior to a new point release.
> Misc fixes

- CHANGELOG.md
- Makefile
- README.md
- project.clj
- src/refactor_nrepl/config.clj
- src/refactor_nrepl/ns/pprint.clj
- test/refactor_nrepl/ns/clean_ns_test.clj
- test/resources/artifacts_pprinted
- test/resources/artifacts_pprinted_traditional_newline
* Upgrade Eastwood, clj-kondo
* Makefile: also use `-user` profile
* This increases reproducibility while developing the project.
* Introduce `:insert-newline-after-require` option
* Context: https://github.com/clojure-emacs/refactor-nrepl/pull/300
> Introduce `:insert-newline-after-require`

- CHANGELOG.md
- src/refactor_nrepl/ns/pprint.clj
- test/refactor_nrepl/ns/clean_ns_test.clj
- test/resources/artifacts_pprinted
- test/resources/artifacts_pprinted_traditional_newline
- test/resources/ns1_cleaned_and_pprinted
This makes the ns form take up less vertical space and makes it easier
on the eyes.
This was never done intentionally, but a side-effect of simply delegating
the printing of regular libspecs to `clojure.core.pprint`, which puts
each element of a vector on its own line when the line gets long enough.
> [Fix #305] No newline after :as or :refer

- src/refactor_nrepl/config.clj
- test/refactor_nrepl/ns/clean_ns_test.clj
- test/resources/ns1_cleaned_and_pprinted_prefix_notation
The default has already been changed in clj-refactor so this is
essentially a no-op, but makes the change more explicit for those
working on the middleware.
> Change default to no prefix re-writing

- CHANGELOG.md
- project.clj
- src/refactor_nrepl/core.clj
- src/refactor_nrepl/find/find_symbol.clj
- test/refactor_nrepl/integration_tests.clj
- test/resources/testproject/src/com/example/five.clj
The edge-case handling for local symbols in opt-maps wasn't using a
reader that was configured correctly and choked on a namespaced keyword.
This PR will also drop support for clojure 1.8:
Destructuring with namespaced keywords was added in clojure 1.9 and
this feature is now referenced in our tests.
According to the state of Clojure 2021 survey only 6.36% of users are
still using this version for development or production.  Since Clojure
is a provided dep in this project they can continue to due so but
'official support' ends as we move to version 3.0.0.
> [#Fix 289] Namespaced keywords vs find (local) symbol 

- test/refactor_nrepl/ns/namespace_aliases_test.clj
It used a single-handed `=`: `(= (some #(= % 'refactor-nrepl.ns.namespace-aliases) ...`, which was making the test invalid.
While I was there, I also DRYed related deftests.
> Fix a test

- CHANGELOG.md
- README.md
- eastwood.clj
- project.clj
- src/refactor_nrepl/analyzer.clj
- src/refactor_nrepl/config.clj
- src/refactor_nrepl/find/find_macros.clj
- src/refactor_nrepl/find/find_symbol.clj
- src/refactor_nrepl/middleware.clj
- src/refactor_nrepl/ns/libspecs.clj
- src/refactor_nrepl/ns/tracker.clj
- src/refactor_nrepl/rename_file_or_dir.clj
- src/refactor_nrepl/util.clj
- test-resources/readable_file_incorrect_aliases.clj
- test-resources/readable_file_incorrect_data_readers.clj
- test-resources/unreadable_file.clj
- test/refactor_nrepl/extract_definition_test.clj
- test/refactor_nrepl/find/find_macros_test.clj
- test/refactor_nrepl/ns/namespace_aliases_test.clj
- test/refactor_nrepl/ns/resolve_missing_caching_test.clj
- test/refactor_nrepl/ns/resolve_missing_test.clj
- test/refactor_nrepl/rename_file_or_dir_test.clj
- test/refactor_nrepl/unreadable_files.clj
Fixes https://github.com/clojure-emacs/refactor-nrepl/issues/291
Interestingly, merely by adding intentionally-invalid .clj files to `test-resources`, all sorts of tests/functionality in the codebase started to break. This surfaced that `wrap-ignore-errors` is pretty necessary, as otherwise it doesn't seem ideal that the occasional odd file in the source path will render refactor-nrepl useless.
This is particularly true for end users that may have not explicitly set the paths to be analyzed (i.e. they may trying to analyze a whole project, not just a subset like `src`/`test`).
The README already advises to set :ignore-errors, so now with this improvement that's more true than ever.
> Introduce `wrap-ignore-errors`

- CHANGELOG.md
- src/refactor_nrepl/find/find_macros.clj
- src/refactor_nrepl/find/find_symbol.clj
- src/refactor_nrepl/ns/tracker.clj
- src/refactor_nrepl/util.clj
Otherwise `future-cancel` wouldn't do much - at least from what I can infer reading the code.
Fixes https://github.com/clojure-emacs/refactor-nrepl/issues/316
> Observe thread interruption status for cancellable tasks

- CHANGELOG.md
- project.clj
- src/refactor_nrepl/analyzer.clj
- test-resources/core_async_usage.clj
- test/refactor_nrepl/analyzer_test.clj
Part of https://github.com/clojure-emacs/refactor-nrepl/issues/245
Performing this `require` makes it more likely that t.ana will succeed. I believe it's becase `require` will also `require` other stuff recursively. t.ana does so in theory as well but it's a bit more rigid.
> Always perform a `require` prior to analyzing a ns

- CHANGELOG.md
- src/refactor_nrepl/core.clj
- src/refactor_nrepl/ns/libspecs.clj
Part of https://github.com/clojure-emacs/refactor-nrepl/issues/230
Parallelizes `referred-syms-by-file&fullname` and `core/` functions used by `referred-syms-by-file&fullname`.
(the `core/` parallelization will be only noticable in large projects)
One can verify the improvement with the following repl input over refactor-nrepl itself:
```clj
(require 'refactor-nrepl.ns.libspecs)
(in-ns 'refactor-nrepl.ns.libspecs)
(time (referred-syms-by-file&fullname true))
```
...It's clearly better than `master` performance for both the non-cached and cached (i.e. subsequent invocations) cases.
(the numbers of course will depend on your CPU count)
> Parallelize `referred-syms-by-file&fullname`

- .circleci/config.yml
- src/refactor_nrepl/core.clj
- test/global_test_setup.clj
- test/refactor_nrepl/core_test.clj
- test/refactor_nrepl/find_symbol_test.clj
- test/refactor_nrepl/integration_tests.clj
- testproject/src/com/example/one.clj
- testproject/src/com/move/ns_to_be_moved.clj
Tries reproducing https://github.com/clojure-emacs/clj-refactor.el/issues/485
`find-symbol` seemed to lack test coverage anyway.
> Add `refactor-nrepl.find-symbol-test`

- project.clj
- src/refactor_nrepl/artifacts.clj
- src/refactor_nrepl/core.clj
- src/refactor_nrepl/middleware.clj
- test/refactor_nrepl/client.clj
In preparation to another PR.
* Upgrade and satisfy Eastwood
* Mainly satisfies `:boxed-math`
* To be clear, it doesn't necessarily always result in a perf gain; it can merely make the underlying boxing more explicit.
* Tests: handle .nrepl-port files with newlines in them
* Make `artifacts-file` cross-OS
* Remove `-Djava.net.preferIPv4Stack=true`
* The build passes without it, and it was preventing a repl from being successfully launched in my environment.
* Use `require-lock` in the last remaining place
> Misc / minor

- src/refactor_nrepl/core.clj
Ensures `pmap` work as intended
I verified that no other places needed a fixing.
> Avoid a lazy `pmap`ping

- CHANGELOG.md
- src/refactor_nrepl/core.clj
- src/refactor_nrepl/ns/libspecs.clj
- src/refactor_nrepl/util.clj
- test/refactor_nrepl/core_test.clj
- test/refactor_nrepl/ns/namespace_aliases_test.clj
- test/refactor_nrepl/util_test.clj
Optimizes this defn via 3 techniques:
* Consolidates the common work to be done across :clj / :cljs dialects
* Parallelizes the work, per dialect
* and shrinks the corpus by removing non source/test dirs from the classpath.
*  (this is the most important gain for small/medium projects)
Testing it over refactor-nrepl itself, I got a performance gain from 70ms (cached case) to 20ms (cached case).
The performance gains can be larger as projects scale. It also can plausibly ameliorate the mistery slowness for the :cljs branch.
Fixes https://github.com/clojure-emacs/refactor-nrepl/issues/230 (see https://github.com/clojure-emacs/refactor-nrepl/issues/230#issuecomment-921093775)
> Optimize `namespace-aliases`

- .clj-kondo/config.edn
- src/refactor_nrepl/middleware.clj
Blast from the past...
Personally I keep using tools.nrepl, I want to stop doing that but can't atm.
These changes help me try the refactor-nrepl alphas before they hit a broader public.
This commit reverts 345fd20 with an additional system property for extra caution.
> Restore tools.nrepl compatibility

- .clj-kondo/config.edn
- Makefile
- project.clj
- src/refactor_nrepl/ns/tracker.clj
- test/refactor_nrepl/ns/tracker_test.clj
`#(str/starts-with? % file-as-absolute-paths)` was invoking the arguments in the wrong order
As a postmortem, sometimes we use defn privacy as a hatch for skipping the authoring of deftests, here it turned out to be too much of an important feature to skip coverage.
While I was there, I also optimized things as bit by absolutizing the refresh-dirs names less redundantly.
> Fix `in-refresh-dirs?`

- README.md
- project.clj
- src/refactor_nrepl/ns/imports_and_refers_analysis.clj
Tracking was excessively obstrusive (it monkey-patched clojure.repl) and coupled (to nrepl middleware).
Now `symbols->ns-syms` doesn't use caching at all, as it ran in less than 1ms anyway.
Similarly `all-ns-imports` has been removed of any caching. This function was a little more expensive (100ms for a medium-sized project), but parallelizing it brings that cost down to 20ms which seems more than acceptable for an end user.
These changes are backed by `refactor-nrepl.ns.imports-and-refers-analysis-test`.
> `imports-and-refers-analysis`: remove tracking and caching

- src/refactor_nrepl/ns/clean_ns.clj
- src/refactor_nrepl/ns/rebuild.clj
- test-resources/cljcns_cleaned.cljc
- test-resources/cljsns_cleaned.cljs
- test-resources/ns1_cleaned_and_pprinted
- test-resources/ns1_cleaned_and_pprinted_prefix_notation
- test/refactor_nrepl/ns/clean_ns_test.clj
Fixes https://github.com/clojure-emacs/refactor-nrepl/issues/344 / rationale there
Not necessarily for merging right away, before I'd like to know if you agree this is a better default?
Should we also provide an option to fall back?
Personally I wouldn't, there doesn't seem to be a huge rationale for the old behavior other than "make things shorter" which seems very relative when considering consistency with other tools or trends over the last few years.
> Don't avoid 1-element vectors/lists

- CHANGELOG.md
- Makefile
- src/refactor_nrepl/config.clj
- src/refactor_nrepl/ns/pprint.clj
- src/refactor_nrepl/ns/rebuild.clj
- test-resources/cljcns.cljc
- test-resources/cljcns_cleaned.cljc
- test/refactor_nrepl/ns/clean_ns_test.clj
- test/refactor_nrepl/ns/rebuild_test.clj
- test/single_segment_ns.clj
* Add `fast-test` Makefile task
* Decouple `ns.pprint` from `clojure.pprint` defaults
* The previous behavior was to wrap around 80 colums. Often teams have a quite more generous column limit (if placing a limit at all), so it's simplest to remain agnostic.
* An option is introduced for reverting to the previous behavior.
* `ns.rebuild`: also wrap single-segment namespace in a vector
* An edge case I found out about just now.
> Refinements for `clean-ns`

- CHANGELOG.md
- project.clj
- src/refactor_nrepl/ns/class_search.clj
- test/refactor_nrepl/ns/class_search_test.clj
Finds more classes (e.g. `FileChannel`), in all JDKs, without needing an extra .jar (like rt.jar, which I was tempted to add for JDK8 but it's a pretty dubious thing to do) in the classpath to be present.
For this we use Compliment's excellent impl which takes care about cross-JDK compat, and some edge cases e.g. Android: https://github.com/alexander-yakushev/compliment/blob/0e0d3e68c665848522d0b6d1f966920dd10ed7ca/src/compliment/utils.clj
Between manual testing and `refactor-nrepl.ns.class-search-test` I'm confident about these changes.
Finally, while Compliment might not be exactly a class searching API, by mrandersoning this dep we can be sure that this feature will never go away.
> Make `ns.class-search` more comprehensive

- CHANGELOG.md
- project.clj
- src/refactor_nrepl/core.clj
- src/refactor_nrepl/fs.clj
- src/refactor_nrepl/rename_file_or_dir.clj
- test/refactor_nrepl/fs_test.clj
- test/refactor_nrepl/ns/class_search_test.clj
These could affect end-users.
Checking out the codebase, we don't ever handle `nio.Path`s so we don't depend on them either.
Uses the flags introduced here: https://github.com/clj-commons/fs/pull/11/files
Fixes https://github.com/clojure-emacs/refactor-nrepl/issues/355
> Disable the extensions performed by `fs`

- CHANGELOG.md
- Makefile
- README.md
- project.clj
Removes warnings for Clojure 1.11 e.g.:
```
WARNING: update-vals already refers to: #'clojure.core/update-vals in namespace: refactor-nrepl.inlined-deps.orchard.v0v7v3.orchard.misc, being replaced by: #'refactor-nrepl.inlined-deps.orchard.v0v7v3.orchard.misc/update-vals
WARNING: update-vals already refers to: #'clojure.core/update-vals in namespace: refactor-nrepl.inlined-deps.toolsanalyzer.v1v0v0.clojure.tools.analyzer.utils, being replaced by: #'refactor-nrepl.inlined-deps.toolsanalyzer.v1v0v0.clojure.tools.analyzer.utils/update-vals
```
> Upgrade some deps

- .circleci/config.yml
About 10 or 20% of CI jobs were failing due to parallelism, which meant that one often had to manually restart builds which would delay releases, etc.
CI runtimes aren't much slower:
> Always use mranderson without parallelism

- CHANGELOG.md
- src/refactor_nrepl/ns/prune_dependencies.clj
- test-resources/defines_deftype.clj
- test-resources/ns1.clj
- test-resources/ns1_cleaned.clj
- test-resources/ns1_cleaned_and_pprinted
- test-resources/ns1_cleaned_and_pprinted_prefix_notation
- test/refactor_nrepl/ns/prune_dependencies_test.clj
Fixes https://github.com/clojure-emacs/refactor-nrepl/issues/194
> Don't prune `require` forms if they are needed for a given `import` to work

- CHANGELOG.md
- README.md
- src/refactor_nrepl/artifacts.clj
- src/refactor_nrepl/middleware.clj
- src/refactor_nrepl/ns/libspecs.clj
- src/refactor_nrepl/ns/ns_parser.clj
- src/refactor_nrepl/ns/suggest_aliases.clj
- src/refactor_nrepl/ns/tracker.clj
- test-resources/bar/ns/libspecs.clj
- test-resources/foo/ns/libspecs.clj
- test-resources/ns/libspecs/cljs_example.cljs
- test/refactor_nrepl/ns/libspecs_test.clj
- test/refactor_nrepl/ns/namespace_aliases_test.clj
- test/refactor_nrepl/ns/suggest_aliases_test.clj
Fixes https://github.com/clojure-emacs/refactor-nrepl/issues/369
I've tried it over my local clj-refactor.el copy and it works smoothly and quickly, aided by the usual measures we take for performance (parallelism, caching)
The gist of the feature is that if I create a _new_ namespace called `my.prefix.foo`, then in another ns I'll be able to type `foo <slash>`, and cljr-slash will insert a `my.prefix.foo :as foo` libspec.
`prefix.foo` would also work, i.e. both `foo` and `prefix.foo` are suggested aliases for `my.prefix.foo`.
Other minor tweaks also included in the PR, one per commit.
> Implement "suggest" option for the `namespace-aliases` op

- CHANGELOG.md
- README.md
- doc/cljdoc.edn
- project.clj
- testproject/src/com/move/dependent_ns1.clj
* Expand `deftest replaces-ns-references-in-dependents`
* Closes https://github.com/clojure-emacs/refactor-nrepl/issues/172, which was already (inadvertently) fixed in https://github.com/clojure-emacs/refactor-nrepl/pull/365.
* Fix cljdoc build
* See: https://github.com/clojure-emacs/orchard/issues/150#issuecomment-1058354437
> Expand `deftest replaces-ns-references-in-dependents`

- CHANGELOG.md
- README.md
- src/refactor_nrepl/ns/libspecs.clj
As indicated in an inline comment:
`namespace-aliases-for` was split out from `namespace-aliases`, for a 3rd-party need.
`namespace-aliases-for` is a little more fine-grained, since it accepts files rather than dirs.
> Extract `namespace-aliases-for`

- CHANGELOG.md
- README.md
- src/refactor_nrepl/ns/libspecs.clj
In a recent refactoring, I introduced `defn namespace-aliases-response`. It should have passed `true` instead of `false`.
Fixes #373
> Revert accidentally-changed `namespace-aliases` error handling default

- CHANGELOG.md
- README.md
- src/refactor_nrepl/ns/prune_dependencies.clj
- test/refactor_nrepl/ns/prune_dependencies_test.clj
Slight oversight from the previous feature.
With these changes, clean-ns will work properly.
> `libspec-in-use-without-refer-all?`: account for `:as-alias` directives

- CHANGELOG.md
- src/refactor_nrepl/ns/suggest_aliases.clj
- test/refactor_nrepl/ns/suggest_aliases_test.clj
Hey there! By pure coincidence, I happened to be investigating a possible bug in `cljr-slash` and `refactor-nrepl.ns.suggest-aliases/suggested-aliases` just as you posted this writeup #384 today, which looks great btw!
I have a project with some namespaces where the last segment starts with a number like `db.migration.005-alter-table`. `suggested-aliases` offers `005-alter-table` as a possible alias, but that's not a valid suggestion since the clojure reader doesn't accept symbols that start with a number. When the nrepl respose is parsed by parseclj, it also correctly rejects that symbol, but that breaks cljr-slash for the entire project.
I put together this little change to remove such invalid symbols from the suggestions, and it's working well for me so far!
Thanks!
> Don't suggest alias fragments with leading number

- .clj-kondo/config.edn
- CHANGELOG.md
- src/refactor_nrepl/core.clj
- src/refactor_nrepl/ns/libspec_allowlist.clj
- src/refactor_nrepl/ns/ns_parser.clj
- src/refactor_nrepl/ns/pprint.clj
- src/refactor_nrepl/ns/prune_dependencies.clj
- test-resources/ns_with_meta_and_attr_map.clj
- test/refactor_nrepl/core_test.clj
- test/refactor_nrepl/ns/libspec_allowlist_test.clj
> https://github.com/clojure-emacs/refactor-nrepl/issues/387
This PR makes refactor-nrepl honor clj-kondo's namespace-local configuration of `:unused-namespace` linter via config.edn file and also via ns meta when performing `clean-ns` task. I'll fix/add tests if code is fine
Thanks!
> Honor clj-kondo's namespace local configuration

- CHANGELOG.md
- Makefile
- README.md
- project.clj
- src/refactor_nrepl/find/find_locals.clj
- src/refactor_nrepl/ns/suggest_libspecs.clj
- test/refactor_nrepl/ns/suggest_libspecs_test.clj
Part of https://github.com/clojure-emacs/clj-refactor.el/issues/556
>  `suggest-libspecs` op: support collections for `:only` values

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- README.md
- src/refactor_nrepl/ns/clean_ns.clj
- test-resources/ns_with_whitespace_changes_only.clj
- test/refactor_nrepl/ns/clean_ns_test.clj
As discussed via Slack earlier today. 
Aside: Looks like the "Code inlining with mranderson" mentioned in the checklist is outdated - there's no `build.sh` (anymore). Instead, I successfully ran `make install` which seems to be equivalent. Maybe this needs to be updated?
> Add always-return-ns-form option to clean-ns

- CHANGELOG.md
- project.clj
- src/refactor_nrepl/ns/class_search.clj
- src/refactor_nrepl/ns/imports_and_refers_analysis.clj
- test/refactor_nrepl/ns/class_search_test.clj
It's only used for finding files on the classpath which comes out of `compliment.utils` namespace. The latter is not really meant for the public use. It's also better to have one fewer dependency. So I've copied the necessary functions into refactor-nrepl.
---
> Stop depending on Compliment
