clojure-emacs/refactor-nrepl

README.md
project.clj
src/refactor_nrepl/client.clj
src/refactor_nrepl/middleware.clj
src/refactor_nrepl/plugin.clj
test/refactor_nrepl/integration_tests.clj

This lets the client know what version of refactor-nrepl it's running on
top of.

Add a version op

---

src/refactor_nrepl/middleware.clj

so that client software which cannot interpret clojure can still
interact with the bencode data

Allow :format "none" to be specified by clients

---

README.md

according to boot's wiki page: https://github.com/boot-clj/boot/wiki/Configuring-Boot#configuring-your-project

Update file path of profile.boot in README.md

---

README.md
project.clj
src/refactor_nrepl/client.clj
src/refactor_nrepl/extract_definition.clj
src/refactor_nrepl/find/bindings.clj
src/refactor_nrepl/find/find_macros.clj
src/refactor_nrepl/find/find_symbol.clj
src/refactor_nrepl/find/find_unbound.clj
src/refactor_nrepl/middleware.clj
src/refactor_nrepl/ns/helpers.clj
src/refactor_nrepl/ns/tracker.clj
src/refactor_nrepl/rename_file_or_dir.clj
src/refactor_nrepl/util.clj
test/refactor_nrepl/find/find_macros_test.clj
test/resources/testproject/src/com/example/aliased_macro_usage.clj
test/resources/testproject/src/com/example/five.clj
test/resources/testproject/src/com/example/fully_qualified_macro_usage.clj
test/resources/testproject/src/com/example/macro_def.clj
test/resources/testproject/src/com/example/referred_macro_usage.clj
test/resources/testproject/src/com/example/shadowed_macro_usages.clj

Make find symbol aware of macros

---

CHANGELOG.md
src/refactor_nrepl/ns/tracker.clj
src/refactor_nrepl/rename_file_or_dir.clj
src/refactor_nrepl/util.clj
test/refactor_nrepl/rename_file_or_dir_test.clj
test/resources/testproject/src/com/move/dependent_ns1_cljs.cljs
test/resources/testproject/src/com/move/dependent_ns2_cljs.cljs
test/resources/testproject/src/com/move/ns_to_be_moved_cljs.cljs
test/resources/testproject/src/com/move/subdir/dependent_ns_3.clj
test/resources/testproject/src/com/move/subdir/dependent_ns_3_cljs.cljs

This also handles the case where we have a macro defined in clojure
which is used in cljs.

Teach rename-file-or-dir how to handle cljs

---

src/refactor_nrepl/ns/rebuild.clj
test/refactor_nrepl/ns/clean_ns_test.clj
test/resources/cljcns_same_clj_cljs.cljc
test/resources/cljcns_same_clj_cljs_cleaned.cljc

Avoid needless .cljc namespace reader macro usage

---

src/refactor_nrepl/ns/slam/hound/search.clj

The (reduce concat ,,,) pattern was causing the stack to overflow, this
was a bit tricky to debug, the symptom was that CIDER would just block
forever.
Also factored out a use of `proxy` so the class generation only needs to
happen once. All in all this version seems to perform significantly
better than the previous one.
(That last point I can't exactly prove since the old version was no longer working for me, so I would appreciate if someone could compare the performance of both versions.  `(get-available-classes)` now runs in <20ms where I seem to remember it being more in 500~1000ms range.)

Replace (reduce concat ,,,) with (mapcat ,,,)

---

src/refactor_nrepl/find/find_symbol.clj

Does this look like an acceptable fix, @benedekfazekas?

[#Fix 167] Only build AST for files on classpath

---

CHANGELOG.md
project.clj

by using forked `alembic` with an updated dynapath dependency

[Fix #169] Fix java9 compatibility

---

CHANGELOG.md
README.md
src/refactor_nrepl/artifacts.clj

- [ x] The commits are consistent with our [contribution guidelines](CONTRIBUTING.md)
- [ x] All tests are passing (run `lein do clean, test`)
Thanks!

Support JVM system proxy in mvn artifacts listing

---

project.clj

Upgrade http-kit to stable. Fixes #237

[Fix #237] upgrade http-kit version to stable

---

README.md

Hopefully it saves someone some frustration down the line (down the lein?).

Mention the minimum version requirement of Leiningen

---

src/refactor_nrepl/ns/rebuild.clj

Fixes clojure-emacs/clj-refactor.el#453

Preserve npm string-style requires for cljr-clean-ns

---

src/refactor_nrepl/ns/slam/hound/regrow.clj

- [ Y] The commits are consistent with our [contribution guidelines](CONTRIBUTING.md)
- [ N] You've added tests (if possible) to cover your change(s)
- [ Y] All tests are passing (run `lein do clean, test`)
- [ Y] Code inlining with mranderson works and tests pass with inlined code (run `./build.sh install` -- takes a long time)
- [ N] You've updated the changelog (if adding/changing user-visible functionality)
- [ N] You've updated the readme (if adding/changing user-visible functionality)
Thanks!

Fix failing tests #282

---

src/refactor_nrepl/artifacts.clj

it fixes https://github.com/clojure-emacs/refactor-nrepl/issues/284
- [?] The commits are consistent with our [contribution guidelines](CONTRIBUTING.md)
- [Y] You've added tests (if possible) to cover your change(s)
- [Y] All tests are passing (run `lein do clean, test`)
- [Y] Code inlining with mranderson works and tests pass with inlined code (run `./build.sh install` -- takes a long time)
- [N] You've updated the changelog (if adding/changing user-visible functionality)
- [N] You've updated the readme (if adding/changing user-visible functionality)

Fix truncated artifacts cache

---

src/refactor_nrepl/ns/rebuild.clj
test/refactor_nrepl/ns/rebuild_test.clj

Fixes https://github.com/clojure-emacs/refactor-nrepl/issues/296

Fix build-cljc-dep-forms with conditionals for only one language 

---

src/refactor_nrepl/find/symbols_in_file.clj
src/refactor_nrepl/ns/clean_ns.clj
test/refactor_nrepl/ns/clean_ns_test.clj
test/resources/ns_with_lots_of_meta.clj
test/resources/ns_with_lots_of_meta_clean.clj

The performance hit in considering literally every piece of metadata
shouldn't be too detrimental so we'll just err on the side of caution
for now.

[Fix #239] Teach clean-ns about more metadata 

---

.clj-kondo/config.edn
Makefile
test/global_test_setup.clj
test/refactor_nrepl/artifacts_test.clj
test/refactor_nrepl/client.clj
test/refactor_nrepl/config_test.clj
test/refactor_nrepl/core_test.clj
test/refactor_nrepl/extract_definition_test.clj
test/refactor_nrepl/find/find_macros_test.clj
test/refactor_nrepl/integration_tests.clj
test/refactor_nrepl/ns/clean_ns_test.clj
test/refactor_nrepl/ns/ns_parser_test.clj
test/refactor_nrepl/rename_file_or_dir_test.clj
test/refactor_nrepl/stubs_for_interface_test.clj
test/refactor_nrepl/util_test.clj

This was harder to accomplish prior to the https://github.com/clojure-emacs/refactor-nrepl/pull/315 splitting

Enable and satisfy clj-kondo in `test/`

---

project.clj
src/refactor_nrepl/artifacts.clj
test/refactor_nrepl/artifacts_test.clj

See also: https://github.com/clojure-emacs/refactor-nrepl/issues/288

Improve http-kit integration / test coverage

---

.circleci/config.yml
README.md
project.clj
src/refactor_nrepl/ns/imports_and_refers_analysis.clj

* 3.0.0-alpha11
* https://clojars.org/refactor-nrepl/versions/3.0.0-alpha11
* Add JDK17 to the CI matrix
* Also bundle https://github.com/clojure-emacs/refactor-nrepl/pull/338
Not sure if this PR is for merging right away. Before a proper 3.0.0 (no alpha) I'd like to add more fixes here and there.

3.0.0-alpha11

---

CHANGELOG.md
src/refactor_nrepl/core.clj
src/refactor_nrepl/find/find_macros.clj
src/refactor_nrepl/find/find_symbol.clj
src/refactor_nrepl/ns/libspecs.clj
src/refactor_nrepl/ns/tracker.clj
test/refactor_nrepl/extract_definition_test.clj

Use source-dirs-on-classpath in more places

---

CHANGELOG.md
src/refactor_nrepl/core.clj
test/refactor_nrepl/core_test.clj
test/refactor_nrepl/ns/resolve_missing_caching_test.clj

Fixes #346, particularly this nuance: https://github.com/clojure-emacs/refactor-nrepl/issues/346#issuecomment-951338268

Refine `source-dirs-on-classpath` heuristic

---

.circleci/config.yml
.circleci/deploy/deploy_release.clj
.circleci/maybe_deploy.clj
CHANGELOG.md
Makefile
README.md
project.clj
resources/refactor_nrepl/version.edn
src/refactor_nrepl/core.clj
test/refactor_nrepl/ns/class_search_test.clj

See also https://github.com/clojure-emacs/cider/discussions/3130
Follows a recipe that has worked well in Eastwood for example.
I also added it to https://github.com/clojure-emacs/enrich-classpath/, works (@bbatsov added the necessary CLOJARS_* variables to a few of our projects)
Updated release instructions in the readme.

Setup deployments on CI

---

.circleci/config.yml
.circleci/deploy/deploy_release.clj
CHANGELOG.md
Makefile

https://clojars.org/refactor-nrepl/versions/3.2.2
```
$ cat /Users/vemv/.m2/repository/refactor-nrepl/refactor-nrepl/3.2.2/refactor-nrepl-3.2.2/refactor_nrepl/version.edn
"3.2.2"%
```

Last batch of deploy tweaks/fixes

---

CHANGELOG.md
src/refactor_nrepl/rename_file_or_dir.clj
test/refactor_nrepl/rename_file_or_dir_test.clj
testproject/src/com/move/dependent_ns1.clj

Fixes https://github.com/clojure-emacs/refactor-nrepl/issues/173

`rename-file-or-dir`: rename more kinds of constructs in dependent namespaces

---

CHANGELOG.md
README.md
src/refactor_nrepl/ns/rebuild.clj
test-resources/as_alias.clj
test/refactor_nrepl/core_test.clj
test/refactor_nrepl/ns/ns_parser_test.clj
test/refactor_nrepl/ns/rebuild_test.clj

Fixes https://github.com/clojure-emacs/refactor-nrepl/issues/374

Support Clojure 1.11's new `:as-alias` namespace directive

---

CHANGELOG.md
README.md
src/refactor_nrepl/find/symbols_in_file.clj
src/refactor_nrepl/ns/ns_parser.clj
test-resources/clean_ns/as_alias.cljc
test/refactor_nrepl/ns/clean_ns_test.clj

Fixes https://github.com/clojure-emacs/refactor-nrepl/issues/378

Fix `:as-alias` handling for .cljc files
